import Game from './Game.js';
import Tile from './Tile.js';
import Wave from './Wave.js';
export default class Map {
    private _element;
    private _game;
    private _tilesXY;
    private _currentWaveIndex;
    private _wavesId;
    private _waves;
    private _tiles;
    private _currentWaves;
    constructor(game: Game);
    get game(): Game;
    get waves(): TJsonWave[];
    get currentWaves(): Wave[];
    set currentWaves(waves: Wave[]);
    get currentWaveIndex(): number;
    get tiles(): Tile[];
    getWaveId(index?: number): number;
    getWave(waveId?: number): TJsonWave;
    private generateTiles;
    private generateDom;
    private addWaves;
    nextWave(): void;
    private createWave;
    private removeWave;
    private waveIteration;
    private isLastWave;
    waveFinished(wave: Wave): void;
    updateStates(timestamp: number): void;
}
