import Tile from './Tile.js';
import Wave from './Wave.js';
import Game from './Game.js';
export default class Map {
    private _game;
    private _element;
    private _nbTiles;
    _arrTiles: Tile[];
    private _jsonMapRoutes;
    private _jsonMonsters;
    private _currentWaveIndex;
    private _waves;
    private _currentWaves;
    private _finished;
    constructor(game: Game);
    get game(): Game;
    get currentWaves(): Wave[];
    set currentWaves(waves: Wave[]);
    get finished(): boolean;
    get waves(): object[];
    get currentWaveIndex(): number;
    generateArrayOfTiles(): Tile[];
    generateWave(): Wave;
    nextWave(): void;
    generateDom(): this;
    getRoutes(): number[][];
    createEvents(): void;
    updateStates(timestamp: number): void;
    waveIteration(fn: (wave: Wave) => void): void;
    waveIteration2(fn: (wave: Wave) => void): void[];
}
